apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
  labels:
    app: ${{values.component_id}}
    component: web
spec:
  selector:
    matchLabels:
      app: ${{values.component_id}}
      component: web
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        component: web
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: ${{values.component_id}}
          image: ghcr.io/devxp-tech/${{values.component_id}} #:devspace
          # image: diegoluisi/${{values.component_id}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
